uploads = []

[[generated]]
id = "YSL07KVN61ZXq6d1N_4SA"
uri = "file://public/images/avatars/cartoon/1.png"
type = "image"
title = "pixel-math-male"

[[generated]]
id = "m21vbuoX3SZDn6SfyOAR8"
uri = "file://public/images/avatars/cartoon/2.png"
type = "image"
title = "pixel-math-female"

[[generated]]
id = "ZRV9DBSGmVjCaGZjUcSxV"
uri = "file://public/images/avatars/cartoon/3.png"
type = "image"
title = "pixel-scientist-male"

[[generated]]
id = "tvh8d09R9NZ8_EmhfScBc"
uri = "file://public/images/avatars/cartoon/4.png"
type = "image"
title = "pixel-scientist-female"

[[generated]]
id = "_xmw5QRTCaR9pdqWQJeTd"
uri = "file://public/images/avatars/cartoon/5.png"
type = "image"
title = "pixel-explorer-male"

[[generated]]
id = "Ui7lUDNx3Yiltpk_gcobK"
uri = "file://public/images/avatars/cartoon/6.png"
type = "image"
title = "pixel-explorer-female"

[[generated]]
id = "MTOHGV4h25DmOtbHpxlW-"
uri = "file://public/images/avatars/cartoon/7.png"
type = "image"
title = "pixel-warrior-male"

[[generated]]
id = "gy8iQ-hWjimQ4ZsMg9fCk"
uri = "file://public/images/avatars/cartoon/8.png"
type = "image"
title = "pixel-warrior-female"

[[generated]]
id = "pt8WD71aXSTtyB13Fl_dO"
uri = "file://public/images/avatars/cartoon/9.png"
type = "image"
title = "pixel-mage-male"

[[generated]]
id = "QDkSDrEUsivYYurg0-MYE"
uri = "file://public/images/avatars/cartoon/10.png"
type = "image"
title = "pixel-mage-female"

[[generated]]
id = "lzxZRulSBi6eh8pesmcut"
uri = "file://public/images/avatars/cartoon/11.png"
type = "image"
title = "pixel-detective-male"

[[generated]]
id = "jiSMEP22GaGyx_evWP9HF"
uri = "file://public/images/avatars/cartoon/12.png"
type = "image"
title = "pixel-detective-female"

[[generated]]
id = "gFjI9Wtqk0kUGmuwp-8Gs"
uri = "file://public/images/avatars/cartoon/13.png"
type = "image"
title = "pixel-knight-male"

[[generated]]
id = "cAnGzT4CJylEytXyE-Q8E"
uri = "file://public/images/avatars/cartoon/14.png"
type = "image"
title = "pixel-knight-female"

[[generated]]
id = "zKLvg9rCmNrS1hl85_CGI"
uri = "file://public/images/avatars/cartoon/15.png"
type = "image"
title = "pixel-robot-male"

[[generated]]
id = "VMPyxGetqvQWFjJCMUGDJ"
uri = "file://public/images/avatars/cartoon/16.png"
type = "image"
title = "pixel-robot-female"

[[generated]]
id = "8EFNLB0KnOfjWYl8eVt0I"
uri = "file://public/images/avatars/cartoon/17.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pebZV9_3ZJW67ChA3BNHJ"
uri = "file://public/images/avatars/cartoon/18.png"
type = "image"
title = "generated_image"

[[generated]]
id = "HJQ5NJh0bFyWWKTGT6uUQ"
uri = "file://public/images/avatars/cartoon/19.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5kxdaRhbCO9xKXH3kCq3H"
uri = "file://public/images/avatars/cartoon/20.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Mep69BojhbLem5ydpGtwq"
uri = "file://public/images/avatars/cartoon/21.png"
type = "image"
title = "generated_image"

[[generated]]
id = "YdwTY89lHTIONFtXpckd6"
uri = "file://public/images/avatars/cartoon/22.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tdjC2ATQc8U6Fkh-7Pkeh"
uri = "file://public/images/avatars/cartoon/23.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2HJBohRTZUu0TX1-pBp5_"
uri = "file://public/images/avatars/cartoon/24.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DcyOGewccOCp5orlqX16u"
uri = "file://public/images/avatars/cartoon/25.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WSQlphPZevLKDQ4HDU3f9"
uri = "file://public/images/avatars/cartoon/26.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UK63j5xk9DlHhc9XuTnpk"
uri = "file://public/images/avatars/portraits/8.png"
type = "image"
title = "generated_image"

[[generated]]
id = "B_unsVR_ITBiWW29DG8u6"
uri = "file://public/images/avatars/portraits/9.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JoKEMyAr5Ure1XvepGErs"
uri = "file://public/images/avatars/portraits/10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "j2CCTj3GM38DufXxxJtXT"
uri = "file://public/images/avatars/portraits/11.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zGd7TLdR3CaHIqsl5Y-i0"
uri = "file://public/images/avatars/portraits/12.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TvUcmKVZJ3CEhmauUVQuH"
uri = "file://public/images/avatars/portraits/13.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sTcYAnvRUHb1iiYTGTthH"
uri = "file://public/images/avatars/portraits/14.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OktzLB8veLDtu-MHYUB5y"
uri = "file://public/images/avatars/portraits/15.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yujK8PvSFff_ov-LxtjAU"
uri = "file://public/images/avatars/portraits/16.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8TNXCM3YW-ChqWprBIXJl"
uri = "file://public/images/avatars/portraits/17.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3KFlMg5zsYmlUdsO-3a4G"
uri = "file://public/images/avatars/portraits/18.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JqHkhAJLTa_zscMiOe5XZ"
uri = "file://public/images/avatars/portraits/19.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hB5Cy9t6QnZzNSwG6iZUw"
uri = "file://public/images/avatars/portraits/20.png"
type = "image"
title = "generated_image"

[[generated]]
id = "S2e37_MtKg3TrYxlPwHoU"
uri = "file://public/images/avatars/portraits/21.png"
type = "image"
title = "generated_image"

[[generated]]
id = "M_noY7JWH3Ft0SK66s3-Z"
uri = "file://public/images/avatars/portraits/22.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dLuGV9aSEZOsgAcrP9zPI"
uri = "file://public/images/avatars/portraits/23.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yEGTy855z6EhLglok2boI"
uri = "file://public/images/avatars/portraits/24.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZZiYUhXlJJDGrcucrWb4h"
uri = "file://public/images/avatars/portraits/25.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MAdSX03Q6unOzZQgMm99D"
uri = "file://public/images/avatars/portraits/26.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "zaB-1zyHMOTGSjJgwse7S"
uri = "file://.local/AUDIT_DUO.md"
type = "text"
title = "Audit Duo — Vérité Node vs Affichage Client"
