<?php

return [
    'regular_opponents' => [
        // Niveaux 1-9 : 🌍 Europe - 8 ans
        1 => ['name' => 'Léa', 'age' => 8, 'avatar' => 'lea', 'next_boss' => 'Le Stratège'],
        2 => ['name' => 'Hugo', 'age' => 8, 'avatar' => 'hugo', 'next_boss' => 'Le Stratège'],
        3 => ['name' => 'Enzo', 'age' => 8, 'avatar' => 'enzo', 'next_boss' => 'Le Stratège'],
        4 => ['name' => 'Nils', 'age' => 8, 'avatar' => 'nils', 'next_boss' => 'Le Stratège'],
        5 => ['name' => 'Zoé', 'age' => 8, 'avatar' => 'zoe', 'next_boss' => 'Le Stratège'],
        6 => ['name' => 'Maël', 'age' => 8, 'avatar' => 'mael', 'next_boss' => 'Le Stratège'],
        7 => ['name' => 'Loris', 'age' => 8, 'avatar' => 'loris', 'next_boss' => 'Le Stratège'],
        8 => ['name' => 'Igor', 'age' => 8, 'avatar' => 'igor', 'next_boss' => 'Le Stratège'],
        9 => ['name' => 'Sven', 'age' => 8, 'avatar' => 'sven', 'next_boss' => 'Le Stratège'],
        
        // Niveaux 11-19 : 🇮🇹 Italie & Méditerranée - 10 ans
        11 => ['name' => 'Luca', 'age' => 10, 'avatar' => 'luca', 'next_boss' => 'La Prodige'],
        12 => ['name' => 'Tazio', 'age' => 10, 'avatar' => 'tazio', 'next_boss' => 'La Prodige'],
        13 => ['name' => 'Giada', 'age' => 10, 'avatar' => 'giada', 'next_boss' => 'La Prodige'],
        14 => ['name' => 'Paolo', 'age' => 10, 'avatar' => 'paolo', 'next_boss' => 'La Prodige'],
        15 => ['name' => 'Rina', 'age' => 10, 'avatar' => 'rina', 'next_boss' => 'La Prodige'],
        16 => ['name' => 'Dario', 'age' => 10, 'avatar' => 'dario', 'next_boss' => 'La Prodige'],
        17 => ['name' => 'Sofia', 'age' => 10, 'avatar' => 'sofia', 'next_boss' => 'La Prodige'],
        18 => ['name' => 'Nino', 'age' => 10, 'avatar' => 'nino', 'next_boss' => 'La Prodige'],
        19 => ['name' => 'Livia', 'age' => 10, 'avatar' => 'livia', 'next_boss' => 'La Prodige'],
        
        // Niveaux 21-29 : 🇬🇧 Anglo-saxon / Irlandais - 12 ans
        21 => ['name' => 'Jack', 'age' => 12, 'avatar' => 'jack', 'next_boss' => 'Le Maître'],
        22 => ['name' => 'Liam', 'age' => 12, 'avatar' => 'liam', 'next_boss' => 'Le Maître'],
        23 => ['name' => 'Alice', 'age' => 12, 'avatar' => 'alice', 'next_boss' => 'Le Maître'],
        24 => ['name' => 'Chloe', 'age' => 12, 'avatar' => 'chloe', 'next_boss' => 'Le Maître'],
        25 => ['name' => 'Ethan', 'age' => 12, 'avatar' => 'ethan', 'next_boss' => 'Le Maître'],
        26 => ['name' => 'Grace', 'age' => 12, 'avatar' => 'grace', 'next_boss' => 'Le Maître'],
        27 => ['name' => 'Mason', 'age' => 12, 'avatar' => 'mason', 'next_boss' => 'Le Maître'],
        28 => ['name' => 'Maria', 'age' => 12, 'avatar' => 'maria', 'next_boss' => 'Le Maître'],
        29 => ['name' => 'Daisy', 'age' => 12, 'avatar' => 'daisy', 'next_boss' => 'Le Maître'],
        
        // Niveaux 31-39 : 🇪🇸 Espagnol / Latino - 14 ans
        31 => ['name' => 'Diego', 'age' => 14, 'avatar' => 'diego', 'next_boss' => 'Le Sage'],
        32 => ['name' => 'Raul', 'age' => 14, 'avatar' => 'raul', 'next_boss' => 'Le Sage'],
        33 => ['name' => 'Rosa', 'age' => 14, 'avatar' => 'rosa', 'next_boss' => 'Le Sage'],
        34 => ['name' => 'Carlos', 'age' => 14, 'avatar' => 'carlos', 'next_boss' => 'Le Sage'],
        35 => ['name' => 'Elena', 'age' => 14, 'avatar' => 'elena', 'next_boss' => 'Le Sage'],
        36 => ['name' => 'Lucia', 'age' => 14, 'avatar' => 'lucia', 'next_boss' => 'Le Sage'],
        37 => ['name' => 'Pablo', 'age' => 14, 'avatar' => 'pablo', 'next_boss' => 'Le Sage'],
        38 => ['name' => 'Wei', 'age' => 14, 'avatar' => 'wei', 'next_boss' => 'Le Sage'],
        39 => ['name' => 'Nelly', 'age' => 14, 'avatar' => 'nelly', 'next_boss' => 'Le Sage'],
        
        // Niveaux 41-49 : 🌏 Asie - 16 ans (diversité ethnique globale)
        41 => ['name' => 'Amina', 'age' => 16, 'avatar' => 'amina', 'next_boss' => 'La Championne'],
        42 => ['name' => 'Alexei', 'age' => 16, 'avatar' => 'alexei', 'next_boss' => 'La Championne'],
        43 => ['name' => 'Amara', 'age' => 16, 'avatar' => 'amara', 'next_boss' => 'La Championne'],
        44 => ['name' => 'Dimitri', 'age' => 16, 'avatar' => 'dimitri', 'next_boss' => 'La Championne'],
        45 => ['name' => 'Katya', 'age' => 16, 'avatar' => 'katya', 'next_boss' => 'La Championne'],
        46 => ['name' => 'Kofi', 'age' => 16, 'avatar' => 'kofi', 'next_boss' => 'La Championne'],
        47 => ['name' => 'Natalia', 'age' => 16, 'avatar' => 'natalia', 'next_boss' => 'La Championne'],
        48 => ['name' => 'Raj', 'age' => 16, 'avatar' => 'raj', 'next_boss' => 'La Championne'],
        49 => ['name' => 'Emi', 'age' => 16, 'avatar' => 'emi', 'next_boss' => 'La Championne'],
        
        // Niveaux 51-59 : 🇨🇳 & 🇰🇷 Asie de l'Est - 18 ans
        51 => ['name' => 'Hana', 'age' => 18, 'avatar' => 'hana', 'next_boss' => 'La Légende'],
        52 => ['name' => 'Joon', 'age' => 18, 'avatar' => 'joon', 'next_boss' => 'La Légende'],
        53 => ['name' => 'Min', 'age' => 18, 'avatar' => 'min', 'next_boss' => 'La Légende'],
        54 => ['name' => 'Yuna', 'age' => 18, 'avatar' => 'yuna', 'next_boss' => 'La Légende'],
        55 => ['name' => 'Tao', 'age' => 18, 'avatar' => 'tao', 'next_boss' => 'La Légende'],
        56 => ['name' => 'Youssef', 'age' => 18, 'avatar' => 'youssef', 'next_boss' => 'La Légende'],
        57 => ['name' => 'Inès', 'age' => 18, 'avatar' => 'ines', 'next_boss' => 'La Légende'],
        58 => ['name' => 'Leilani', 'age' => 18, 'avatar' => 'leilani', 'next_boss' => 'La Légende'],
        59 => ['name' => 'Venetia', 'age' => 18, 'avatar' => 'venetia', 'next_boss' => 'La Légende'],
        
        // Niveaux 61-69 : 🌍 Afrique / Moyen-Orient - 20 ans
        61 => ['name' => 'Aziz', 'age' => 20, 'avatar' => 'aziz', 'next_boss' => 'Le Titan'],
        62 => ['name' => 'Amel', 'age' => 20, 'avatar' => 'amel', 'next_boss' => 'Le Titan'],
        63 => ['name' => 'Idris', 'age' => 20, 'avatar' => 'idris', 'next_boss' => 'Le Titan'],
        64 => ['name' => 'Yara', 'age' => 20, 'avatar' => 'yara', 'next_boss' => 'Le Titan'],
        65 => ['name' => 'Noura', 'age' => 20, 'avatar' => 'noura', 'next_boss' => 'Le Titan'],
        66 => ['name' => 'Samir', 'age' => 20, 'avatar' => 'samir', 'next_boss' => 'Le Titan'],
        67 => ['name' => 'Karim', 'age' => 20, 'avatar' => 'karim', 'next_boss' => 'Le Titan'],
        68 => ['name' => 'Colin', 'age' => 20, 'avatar' => 'colin', 'next_boss' => 'Le Titan'],
        69 => ['name' => 'Rubie', 'age' => 20, 'avatar' => 'rubie', 'next_boss' => 'Le Titan'],
        
        // Niveaux 71-79 : 🌎 Amériques / Polynésie / Autres - 22 ans
        71 => ['name' => 'Maya', 'age' => 22, 'avatar' => 'maya', 'next_boss' => 'La Virtuose'],
        72 => ['name' => 'Tane', 'age' => 22, 'avatar' => 'tane', 'next_boss' => 'La Virtuose'],
        73 => ['name' => 'Lilo', 'age' => 22, 'avatar' => 'lilo', 'next_boss' => 'La Virtuose'],
        74 => ['name' => 'Naya', 'age' => 22, 'avatar' => 'naya', 'next_boss' => 'La Virtuose'],
        75 => ['name' => 'Ari', 'age' => 22, 'avatar' => 'ari', 'next_boss' => 'La Virtuose'],
        76 => ['name' => 'Milo', 'age' => 22, 'avatar' => 'milo', 'next_boss' => 'La Virtuose'],
        77 => ['name' => 'Kira', 'age' => 22, 'avatar' => 'kira', 'next_boss' => 'La Virtuose'],
        78 => ['name' => 'Elsa', 'age' => 22, 'avatar' => 'elsa', 'next_boss' => 'La Virtuose'],
        79 => ['name' => 'Erik', 'age' => 22, 'avatar' => 'erik', 'next_boss' => 'La Virtuose'],
        
        // Niveaux 81-89 : Mix (noms restants) - 24 ans
        81 => ['name' => 'Lara', 'age' => 24, 'avatar' => 'lara', 'next_boss' => 'Le Génie'],
        82 => ['name' => 'Noa', 'age' => 24, 'avatar' => 'noa', 'next_boss' => 'Le Génie'],
        83 => ['name' => 'Aisha', 'age' => 24, 'avatar' => 'aisha', 'next_boss' => 'Le Génie'],
        84 => ['name' => 'Kenji', 'age' => 24, 'avatar' => 'kenji', 'next_boss' => 'Le Génie'],
        85 => ['name' => 'Priya', 'age' => 24, 'avatar' => 'priya', 'next_boss' => 'Le Génie'],
        86 => ['name' => 'Koa', 'age' => 24, 'avatar' => 'koa', 'next_boss' => 'Le Génie'],
        87 => ['name' => 'Rena', 'age' => 24, 'avatar' => 'rena24', 'next_boss' => 'Le Génie'],
        88 => ['name' => 'Ming', 'age' => 24, 'avatar' => 'ming', 'next_boss' => 'Le Génie'],
        89 => ['name' => 'Antoine', 'age' => 24, 'avatar' => 'antoine', 'next_boss' => 'Le Génie'],
        
        // Niveaux 91-99 : Mix (derniers noms) - 26 ans
        91 => ['name' => 'Mateo', 'age' => 26, 'avatar' => 'mateo26', 'next_boss' => "L'Intelligence Ultime"],
        92 => ['name' => 'Leila', 'age' => 26, 'avatar' => 'leila26', 'next_boss' => "L'Intelligence Ultime"],
        93 => ['name' => 'Axel', 'age' => 26, 'avatar' => 'axel', 'next_boss' => "L'Intelligence Ultime"],
        94 => ['name' => 'Lian', 'age' => 26, 'avatar' => 'lian', 'next_boss' => "L'Intelligence Ultime"],
        95 => ['name' => 'Jorge', 'age' => 26, 'avatar' => 'jorge', 'next_boss' => "L'Intelligence Ultime"],
        96 => ['name' => 'Miki', 'age' => 26, 'avatar' => 'miki', 'next_boss' => "L'Intelligence Ultime"],
        97 => ['name' => 'Dalia', 'age' => 26, 'avatar' => 'dalia', 'next_boss' => "L'Intelligence Ultime"],
        98 => ['name' => 'Ivan', 'age' => 26, 'avatar' => 'ivan', 'next_boss' => "L'Intelligence Ultime"],
        99 => ['name' => 'Théo', 'age' => 26, 'avatar' => 'theo', 'next_boss' => "L'Intelligence Ultime"],
    ],
    
    'boss_opponents' => [
        10 => [
            'name' => 'Le Stratège', 
            'slug' => 'le-stratege',
            'abstention' => 90,
            'description' => "Penseur méthodique, il ne buzzera jamais par impulsion. Chaque mouvement est calculé. Hésite longuement sur ce qu'il ne maîtrise pas parfaitement et déteste perdre des points inutilement. Sous pression, il se paralyse et laisse passer encore plus d'opportunités. Si vous menez, il se renferme complètement.",
            'radar' => [
                'Général' => 70,
                'Cinéma' => 55,
                'Science' => 65,
                'Géographie' => 75,
                'Histoire' => 70,
                'Art' => 50,
                'Culture' => 60,
                'Sport' => 62,
                'Cuisine' => 43,
            ]
        ],
        20 => [
            'name' => 'La Prodige', 
            'slug' => 'la-prodige',
            'abstention' => 85,
            'description' => "Mélange déconcertant de brillance et de doutes. Enchaîne trois buzz fulgurants puis hésite sur une question facile. Redoutable sur ses domaines forts (culture, cinéma, art), mais se retire ailleurs. Son talent compense au début, mais elle fatigue mentalement très vite. Plus le match s'étire, plus sa concentration s'effrite.",
            'radar' => [
                'Général' => 70,
                'Cinéma' => 78,
                'Science' => 58,
                'Géographie' => 55,
                'Histoire' => 52,
                'Art' => 72,
                'Culture' => 82,
                'Sport' => 48,
                'Cuisine' => 59,
            ]
        ],
        30 => [
            'name' => 'Le Maître', 
            'slug' => 'le-maitre',
            'abstention' => 80,
            'description' => "Ne se laisse pas intimider et sait gérer les émotions du jeu. Lit le rythme de la partie et adapte sa stratégie en temps réel. Patient quand il le faut, opportuniste au bon moment. Faiblesse : l'âge. Après quinze questions, ses réflexes ralentissent et sa vitesse de lecture diminue visiblement. Faites durer le match.",
            'radar' => [
                'Général' => 75,
                'Cinéma' => 62,
                'Science' => 68,
                'Géographie' => 78,
                'Histoire' => 82,
                'Art' => 58,
                'Culture' => 72,
                'Sport' => 54,
                'Cuisine' => 64,
            ]
        ],
        40 => [
            'name' => 'Le Sage', 
            'slug' => 'le-sage',
            'abstention' => 75,
            'description' => "Accepte l'échec comme partie du jeu, ce qui le rend imprévisible. Alterne prudence et audace selon une logique propre. Sait mieux que quiconque quand risquer ou reculer. Si vous menez, il doute de sa stratégie et prend des risques inhabituels pour rattraper. C'est là qu'il commet des erreurs fatales.",
            'radar' => [
                'Général' => 78,
                'Cinéma' => 62,
                'Science' => 82,
                'Géographie' => 70,
                'Histoire' => 85,
                'Art' => 65,
                'Culture' => 75,
                'Sport' => 55,
                'Cuisine' => 72,
            ]
        ],
        50 => [
            'name' => 'La Championne', 
            'slug' => 'la-championne',
            'abstention' => 70,
            'description' => "Joue pour écraser, pas pour participer. Pression offensive constante dès la première question. Buzz rapides, tempo infernal. Son endurance lui permet de tenir ce rythme longtemps. Si vous la dominez, son esprit de compétition devient son pire ennemi : elle panique, buzz trop vite, commet des erreurs stupides.",
            'radar' => [
                'Général' => 80,
                'Cinéma' => 68,
                'Science' => 65,
                'Géographie' => 74,
                'Histoire' => 78,
                'Art' => 72,
                'Culture' => 80,
                'Sport' => 88,
                'Cuisine' => 71,
            ]
        ],
        60 => [
            'name' => 'La Légende', 
            'slug' => 'la-legende',
            'abstention' => 65,
            'description' => "Sa réputation la précède. Buzz même dans l'incertitude pour impressionner et déstabiliser. Son charisme fait partie de l'arsenal. Confiante au point de l'arrogance. Si vous la menez, elle refuse d'admettre le danger et persiste dans ses méthodes en les poussant encore plus loin, creusant son propre piège.",
            'radar' => [
                'Général' => 85,
                'Cinéma' => 82,
                'Science' => 72,
                'Géographie' => 78,
                'Histoire' => 80,
                'Art' => 75,
                'Culture' => 85,
                'Sport' => 70,
                'Cuisine' => 73,
            ]
        ],
        70 => [
            'name' => 'Le Titan', 
            'slug' => 'le-titan',
            'abstention' => 60,
            'description' => "Préparez-vous à une avalanche. Buzz tout, répond à tout, pression maximale dès la première seconde. Sa stratégie : vous écraser mentalement. Il compte sur sa puissance pure. Mais il joue à fond d'entrée. Si le match s'éternise au-delà de 20 questions, il s'effondre brutalement : tout donné trop tôt, rien en réserve.",
            'radar' => [
                'Général' => 88,
                'Cinéma' => 75,
                'Science' => 85,
                'Géographie' => 80,
                'Histoire' => 82,
                'Art' => 74,
                'Culture' => 80,
                'Sport' => 78,
                'Cuisine' => 76,
            ]
        ],
        80 => [
            'name' => 'La Virtuose', 
            'slug' => 'la-virtuose',
            'abstention' => 55,
            'description' => "Ne joue pas que pour gagner, mais pour créer du spectacle. Chaque buzz chorégraphié, chaque réponse une performance. Préfère une défaite élégante à une victoire ennuyeuse. Ultra confiante, hésite rarement. Sous stress, son perfectionnisme paralyse : cherche LA formulation parfaite au lieu de buzzer vite.",
            'radar' => [
                'Général' => 90,
                'Cinéma' => 88,
                'Science' => 78,
                'Géographie' => 82,
                'Histoire' => 84,
                'Art' => 92,
                'Culture' => 90,
                'Sport' => 72,
                'Cuisine' => 82,
            ]
        ],
        90 => [
            'name' => 'Le Génie', 
            'slug' => 'le-genie',
            'abstention' => 50,
            'description' => "Ne joue pas au feeling, calcule des probabilités en temps réel. Pendant que vous lisez, il analyse déjà les réponses possibles. Teste ses adversaires avec des buzz calculés. Même 50% d'incertitude devient jouable. Faiblesse : pense trop. Calcule tant de variables qu'il rate l'évidence. La fatigue amplifie ce défaut.",
            'radar' => [
                'Général' => 92,
                'Cinéma' => 82,
                'Science' => 95,
                'Géographie' => 86,
                'Histoire' => 88,
                'Art' => 80,
                'Culture' => 85,
                'Sport' => 75,
                'Cuisine' => 84,
            ]
        ],
        100 => [
            'name' => "L'Intelligence Ultime", 
            'slug' => 'intelligence-ultime',
            'abstention' => 45,
            'description' => "Transcende la compétition normale. Traite l'information plus vite que la lecture. Buzz instantanés, précision terrifiante, vitesse surhumaine. Ne connaît pas l'hésitation. Mais si vous le menez, assistez à un effondrement catastrophique : l'impensable se produit, il perd tous ses repères, buzz n'importe quoi, précision en chute libre.",
            'radar' => [
                'Général' => 95,
                'Cinéma' => 85,
                'Science' => 98,
                'Géographie' => 90,
                'Histoire' => 92,
                'Art' => 82,
                'Culture' => 88,
                'Sport' => 78,
                'Cuisine' => 86,
            ]
        ],
    ],
];
