<?php

declare(strict_types=1);

namespace App\Services\QuestionBank\Quarantine;

use App\Services\QuestionBank\KernelBlueprint;
use App\Services\QuestionBank\KernelBlueprintCognitiveSlotRepository;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use LogicException;

/**
 * Transactional backend for the Admin quarantine actions.  This is an
 * application service, not an HTTP controller and intentionally has no view
 * concerns.
 */
final class KernelQuarantineAdminService
{
    public function __construct(
        private readonly KernelQuarantineWorkCopyRepository $copies = new KernelQuarantineWorkCopyRepository(),
        private readonly KernelQuarantineWorkCopySlotRepository $copySlots = new KernelQuarantineWorkCopySlotRepository(),
        private readonly KernelQuarantineSlotResumptionRepository $resumptions = new KernelQuarantineSlotResumptionRepository(),
    ) {}

    /**
     * Snapshot the complete seven-slot aggregate before clearing suspect
     * canonical positions.  The returned revision is the canonical revision
     * observed while the snapshot was made.
     *
     * @return array{copy_id:string, copy_version:int, canonical_base_revision:int}
     */
    public function createCopyFromCanonical(string $blueprintId, string $originPhase = 'VALIDATION_PHASE1'): array
    {
        return DB::transaction(function () use ($blueprintId, $originPhase): array {
            $run = DB::table('kernel_blueprint_runs')->where('blueprint_id', $blueprintId)->lockForUpdate()->first();
            if ($run === null) {
                throw new LogicException("Blueprint canonique introuvable: {$blueprintId}.");
            }
            $slots = DB::table('kernel_blueprint_cognitive_slots')
                ->where('blueprint_id', $blueprintId)->lockForUpdate()->get()->keyBy('cognitive_type');
            if ($slots->count() !== 7 || array_diff(KernelBlueprint::COGNITIVE_TYPES, $slots->keys()->all()) !== []) {
                throw new LogicException('Le Blueprint canonique doit posséder exactement sept slots.');
            }
            $baseRevision = 0;
            foreach ($slots as $row) {
                $baseRevision = max($baseRevision, (int) ($row->canonical_revision ?? 0));
            }
            $copyId = (string) Str::orderedUuid();
            $this->copies->create([
                'blueprint_id' => $blueprintId,
                'kernel_code' => (string) ($run->kernel_code ?? ''),
                'depth' => $run->depth ?? null,
                'domain_code' => $run->domain_code ?? null,
                'subdomain_active' => $run->subdomain_active ?? null,
                'subject_active' => $run->subject_active ?? null,
                'dominant_idea_active' => $run->dominant_idea_active ?? null,
                'origin_phase' => $originPhase,
            ], $copyId);

            foreach (KernelBlueprint::COGNITIVE_TYPES as $type) {
                $row = $slots->get($type);
                $this->copySlots->insert($copyId, $type, [
                    'source' => $this->decode($row->source) ?? KernelBlueprint::emptyCognitiveSlotSource($type),
                    'creation_failure' => $this->decode($row->creation_failure),
                    'translations' => $this->decode($row->translations) ?? [],
                    'creation_status' => $row->creation_status,
                    'validation_status' => $row->validation_status,
                    'validation_findings' => $this->decode($row->validation_findings) ?? [],
                    'canonical_base_revision' => (int) ($row->canonical_revision ?? 1),
                    'slot_revision' => 1,
                ]);
            }

            // Only red positions are emptied.  A source skeleton is always
            // generated by the official type, never by an arbitrary object.
            foreach ($slots as $row) {
                if ((string) $row->validation_status !== 'SUSPICION'
                    && (string) $row->creation_status !== 'EMPTY') {
                    continue;
                }
                $values = [
                        'source' => json_encode(KernelBlueprint::emptyCognitiveSlotSource((string) $row->cognitive_type), JSON_THROW_ON_ERROR),
                        'creation_failure' => null,
                        'translations' => '{}',
                        'creation_status' => 'EMPTY',
                        'validation_status' => 'NOT_VALIDATED',
                        'validation_findings' => '[]',
                        'updated_at' => now(),
                    ];
                if (DB::getDriverName() !== 'pgsql'
                    && Schema::hasColumn('kernel_blueprint_cognitive_slots', 'canonical_revision')) {
                    $values['canonical_revision'] = DB::raw('canonical_revision + 1');
                }
                if (DB::getDriverName() === 'pgsql') {
                    $returned = DB::selectOne(
                        'UPDATE kernel_blueprint_cognitive_slots
                         SET source = ?, creation_failure = ?, translations = ?,
                             creation_status = ?, validation_status = ?,
                             validation_findings = ?, updated_at = ?
                         WHERE blueprint_id = ? AND cognitive_type = ?
                         RETURNING canonical_revision',
                        [
                            $values['source'], $values['creation_failure'], $values['translations'],
                            $values['creation_status'], $values['validation_status'],
                            $values['validation_findings'], $values['updated_at'],
                            $blueprintId, $row->cognitive_type,
                        ],
                    );
                    $canonicalRevision = (int) $returned->canonical_revision;
                } else {
                    DB::table('kernel_blueprint_cognitive_slots')
                        ->where('blueprint_id', $blueprintId)
                        ->where('cognitive_type', $row->cognitive_type)
                        ->update($values);
                    $canonicalRevision = (int) DB::table('kernel_blueprint_cognitive_slots')
                        ->where('blueprint_id', $blueprintId)
                        ->where('cognitive_type', $row->cognitive_type)
                        ->value('canonical_revision');
                }
                DB::table('kernel_quarantine_work_copy_slots')
                    ->where('copy_id', $copyId)
                    ->where('cognitive_type', $row->cognitive_type)
                    ->update(['canonical_base_revision' => $canonicalRevision, 'updated_at' => now()]);
            }
            return [
                'copy_id' => $copyId,
                'copy_version' => 1,
                'canonical_base_revision' => $baseRevision,
            ];
        });
    }

    /** Alias used by callers which name the action after its domain term. */
    public function quarantine(string $blueprintId, string $originPhase = 'VALIDATION_PHASE1'): array
    {
        return $this->createCopyFromCanonical($blueprintId, $originPhase);
    }

    /**
     * Edit any slot.  Editing invalidates PASS and findings and creates the
     * exact persistent yellow resumption index.
     *
     * @param array<string,mixed> $patch
     * @return array{copy_id:string,copy_version:int,manual_revision:int,canonical_base_revision:int}
     */
    public function editSlot(
        string $copyId,
        string $cognitiveType,
        array $patch,
        int $expectedCopyVersion,
        ?int $expectedManualRevision = null,
        ?int $expectedCanonicalBaseRevision = null
    ): array {
        return DB::transaction(function () use ($copyId, $cognitiveType, $patch, $expectedCopyVersion, $expectedManualRevision, $expectedCanonicalBaseRevision): array {
            $copy = $this->copies->find($copyId, true);
            if ($copy === null || ! in_array((string) $copy->state, ['EDITABLE', 'READY'], true)
                || (int) $copy->copy_version !== $expectedCopyVersion) {
                throw new LogicException('Référence de copie Quarantaine périmée.');
            }
            $slot = DB::table('kernel_quarantine_work_copy_slots')
                ->where('copy_id', $copyId)->where('cognitive_type', $cognitiveType)
                ->lockForUpdate()->first();
            if ($slot === null) {
                throw new LogicException("Slot Quarantaine absent: {$cognitiveType}.");
            }
            if ($expectedManualRevision !== null && (int) $slot->manual_revision !== $expectedManualRevision) {
                throw new LogicException('Révision manuelle périmée.');
            }
            $canonical = DB::table('kernel_blueprint_cognitive_slots')
                ->where('blueprint_id', $copy->blueprint_id)
                ->where('cognitive_type', $cognitiveType)
                ->lockForUpdate()->first();
            if ($canonical === null) {
                throw new LogicException('Slot canonique absent.');
            }
            $expectedBase = $expectedCanonicalBaseRevision
                ?? (int) $slot->canonical_base_revision;
            if ($expectedCanonicalBaseRevision !== null
                && (int) $slot->canonical_base_revision !== $expectedCanonicalBaseRevision) {
                throw new LogicException('Révision canonique Quarantaine périmée.');
            }
            if ((int) $canonical->canonical_revision !== $expectedBase) {
                throw new LogicException('Révision canonique Quarantaine périmée.');
            }
            // A previously green slot is no longer trusted the instant an
            // Admin edits it.  Clear only that canonical position, using the
            // official type skeleton, in the same transaction as the copy
            // mutation.  Other six positions are never projected.
            if ((string) ($slot->color ?? '') === 'GREEN') {
                $canonicalValues = [
                    'source' => json_encode(KernelBlueprint::emptyCognitiveSlotSource($cognitiveType), JSON_THROW_ON_ERROR),
                    'creation_failure' => null,
                    'translations' => '{}',
                    'creation_status' => 'EMPTY',
                    'validation_status' => 'NOT_VALIDATED',
                    'validation_findings' => '[]',
                    'updated_at' => now(),
                ];
                if (DB::getDriverName() !== 'pgsql'
                    && Schema::hasColumn('kernel_blueprint_cognitive_slots', 'canonical_revision')) {
                    $canonicalValues['canonical_revision'] = DB::raw('canonical_revision + 1');
                }
                $canonicalUpdated = DB::table('kernel_blueprint_cognitive_slots')
                    ->where('blueprint_id', $copy->blueprint_id)
                    ->where('cognitive_type', $cognitiveType)
                    ->where('canonical_revision', $expectedBase)
                    ->update($canonicalValues);
                if ($canonicalUpdated !== 1) {
                    throw new LogicException('Révision canonique Quarantaine périmée.');
                }
            }
            $revision = (int) $slot->manual_revision + 1;
            $newVersion = $this->copies->bumpVersion($copyId, $expectedCopyVersion);
            $patch['validation_status'] = 'NOT_VALIDATED';
            $patch['validation_findings'] = [];
            $this->copySlots->updateManual($copyId, $cognitiveType, $patch, $expectedCopyVersion, $revision);
            $this->resumptions->upsert($copyId, $cognitiveType, $newVersion, $revision);
            DB::table('kernel_current_kernel_dispatches')
                ->where('copy_id', $copyId)->where('state', 'READY')
                ->update(['copy_version' => $newVersion, 'updated_at' => now()]);
            $canonicalRevision = (int) DB::table('kernel_blueprint_cognitive_slots')
                ->where('blueprint_id', $copy->blueprint_id)
                ->where('cognitive_type', $cognitiveType)
                ->value('canonical_revision');
            return [
                'copy_id' => $copyId,
                'copy_version' => $newVersion,
                'manual_revision' => $revision,
                'canonical_base_revision' => $canonicalRevision,
            ];
        });
    }

    /** Enqueue is idempotent per copy and never starts Phase 1. */
    /** @return array{dispatch_id:string,event_id:string} */
    public function enqueue(string $copyId, int $expectedCopyVersion, ?string $eventId = null): array
    {
        return DB::transaction(function () use ($copyId, $expectedCopyVersion, $eventId): array {
            $copy = $this->copies->find($copyId, true);
            if ($copy === null || (int) $copy->copy_version !== $expectedCopyVersion
                || ! in_array((string) $copy->state, ['EDITABLE', 'READY'], true)) {
                throw new LogicException('Version de copie périmée.');
            }
            $existing = DB::table('kernel_current_kernel_dispatches')
                ->where('copy_id', $copyId)->first();
            if ($existing !== null) {
                return ['dispatch_id' => (string) $existing->event_id, 'event_id' => (string) $existing->event_id];
            }
            $eventId ??= (string) Str::orderedUuid();
            $order = DB::getDriverName() === 'pgsql'
                ? (int) DB::selectOne("SELECT nextval('kernel_quarantine_ready_order_seq') AS value")->value
                : (int) DB::table('kernel_quarantine_work_copies')->max('ready_order') + 1;
            $this->copies->setReadyRequest($copyId, $eventId, $order);
            DB::table('kernel_current_kernel_dispatches')->insert([
                'event_id' => $eventId,
                'blueprint_id' => $copy->blueprint_id,
                'direction' => KernelCurrentKernelReceivedRouter::QUARANTINE,
                'copy_id' => $copyId,
                'copy_version' => $expectedCopyVersion,
                'ready_order' => $order,
                'state' => 'READY',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            return ['dispatch_id' => $eventId, 'event_id' => $eventId];
        });
    }

    /** Explicit backend naming used by Admin adapters. */
    public function updateSlot(
        string $copyId,
        string $cognitiveType,
        array $patch,
        int $expectedCopyVersion,
        ?int $expectedManualRevision = null,
        ?int $expectedCanonicalBaseRevision = null
    ): array {
        return $this->editSlot(
            $copyId,
            $cognitiveType,
            $patch,
            $expectedCopyVersion,
            $expectedManualRevision,
            $expectedCanonicalBaseRevision,
        );
    }

    private function decode(mixed $value): ?array
    {
        if ($value === null || is_array($value)) {
            return $value;
        }
        $decoded = json_decode((string) $value, true);
        return is_array($decoded) ? $decoded : null;
    }
}